# Cover configurations

# Relay configuration
switch:
  - platform: gpio
    name: Garageportrelä
    id: gd_relay
    icon: mdi:garage-variant
    pin:
      number: GPIO21
      mode:
        output: true
    on_turn_on:
      - delay: 800ms
      - switch.turn_off: gd_relay

# End stop sensor configuration
binary_sensor:
  # Garage door open
  - platform: gpio
    name: Garageport öppen
    id: gd_open_position
    pin:
      number: GPIO17
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on_off: 400ms
    on_press:
      - lambda: |-
          id(gd_garage_door).publish_state(COVER_OPEN);
  # Garage door closed
  - platform: gpio
    name: Garageport stängd
    id: gd_closed_position
    pin:
      number: GPIO16
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on_off: 400ms
    on_press:
      - lambda: |-
          id(gd_garage_door).publish_state(COVER_CLOSED);
  # Garage door intermediate position
  - platform: template
    id: gd_intermediate_position
    lambda: |-
      if ( (id(gd_open_position).state == false) && 
           (id(gd_closed_position).state == false) ) {
        return true;
      } else {
        return false;
      }
  # Garage door external open/close switch
  - platform: gpio
    name: Garageport manövrering
    id: gd_external_switch
    pin:
      number: GPIO19
      inverted: false
      mode:
        input: true
        pulldown: true
    filters:
      - delayed_on_off: 400ms
    on_press:
      - switch.turn_on: gd_relay

# Cover operation configuration
cover:
  - platform: endstop
    name: Garageport
    id: gd_garage_door
    device_class: garage
    # Open garage door
    open_action:
      - switch.turn_on: gd_relay
    open_duration: 22s
    open_endstop: gd_open_position
    # Close garage door
    close_action:
      - switch.turn_on: gd_relay
    close_duration: 22s
    close_endstop: gd_closed_position
    # Stop garage door
    stop_action:
      - lambda: |-
          if ( id(gd_intermediate_position).state ) {
            id(gd_relay).turn_on();
          }
