#
# ESP32 Garage Door Controller
#
# https://github.com/jnasholm/gdc/tree/main
#
# Main configuration
#
substitutions:
  node_name: gdr1
  node_prefix: GD

# Define zone id and name
  zone_id:   garage
  zone_name: RK Garage

# Board configuration
esphome:
  project:
    name: "jnasholm.gdc"
    version: "0.1"
  name: $node_name
  platform: ESP32
  board: esp32-devkitlipo
#  board: esp32-poe-iso

# Flash write interval
preferences:
  flash_write_interval: 20min

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret hass_api_key

# Enable OTA
ota:
  password: !secret ota_password

# Node switches
switch:
  - platform: restart
    name: $node_prefix starta om nod
#  - platform: shutdown
#    name: $node_prefix st??ng av nod

# Node uptime
sensor:
  - platform: uptime
    name: $node_prefix drifttid
    icon: mdi:timer-outline
    update_interval: 60s

# Include packages
packages:
  wifi: !include wifi.yaml
#  ethernet: !include ethernet.yaml
#  battery: !include battery.yaml
  time: !include time.yaml
  status: !include status.yaml
  cover: !include cover.yaml
  room_climate: !include sensors-room_climate.yaml
