# Status configuration

# Controller status indicator
output:
  - platform: ledc
    id: ${node_name}_controller_status
    pin: GPIO33

# System status indicator
light:
  - platform: status_led
    name: $node_prefix systemstatus
    id: ${node_name}_system_status_indicator
    pin:
      number: GPIO32
      inverted: true
# Controller status indicator
  - platform: monochromatic
    name: $node_prefix reglerstatus
    id: ${node_name}_controller_status_indicator
    output: ${node_name}_controller_status
    effects:
      - pulse:
          name: active_mode
          transition_length: 0.2s
          update_interval: 0.8s
      - pulse:
          name: idle_mode
          transition_length: 0.2s
          update_interval: 4s

# Controller operational state indication
binary_sensor:
  - platform: template
    id: ${node_name}_controller_state
    lambda: |-
      if ( id(gd_intermediate_position).state ) {
        return true;
      } else {
        return false;
      }
    on_press:
      - light.turn_on:
          id: ${node_name}_controller_status_indicator
          effect: active_mode
    on_release:
      - light.turn_on:
          id: ${node_name}_controller_status_indicator
          effect: idle_mode


#      if ( id(gd_intermediate_position).state ) {
#          id(controller_status_indicator).turn_on().set_effect(active_mode).perform();
#          return true;
#      } else if ( id(gd_relay).state ) {
#          id(controller_status_indicator).turn_on();
#          return true;
#      } else {
#          id(controller_status_indicator).turn_off();
#          return false;
#      }
