# Status configuration

# Controller status indicator
output:
  - platform: ledc
    id: garage_door_controller_status
    pin: GPIO33

# System status indicator
light:
  - platform: status_led
    name: $node_prefix systemstatus
    id: system_status_indicator
    pin:
      number: GPIO32
      inverted: true
  # Relay status indicator
  - platform: monochromatic
    name: $node_prefix reglerstatus
    id: controller_status_indicator
    output: garage_door_controller_status
    effects:
      - pulse:
          name: active
          transition_length: 0.2s
          update_interval: 0.8s
      - pulse:
          name: idle
          transition_length: 0.2s
          update_interval: 4s

# Controller operational state
binary_sensor:
  - platform: template
    id: garage_door_controller_state
    lambda: |-
      if ( id(gd_intermediate_position).state ) {
          id(controller_status_indicator).turn_on().set_effect("active").perform();
          return true;
      } else if ( id(gd_relay).state ) {
          id(controller_status_indicator).turn_on();
          return true;
      } else {
          id(controller_status_indicator).turn_off();
          return false;
      }
